// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2H52ETHWW54QwMjBER16VbBsYISNv6qU',
    appId: '1:274499137654:web:194b16e479aeb79cd82f57',
    messagingSenderId: '274499137654',
    projectId: 'uberclone-4eb43',
    authDomain: 'uberclone-4eb43.firebaseapp.com',
    databaseURL: 'https://uberclone-4eb43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uberclone-4eb43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsLTffO5uEwbDgvr3rTDvuTz5SRxtWtrs',
    appId: '1:274499137654:android:41e83fe6eec94864d82f57',
    messagingSenderId: '274499137654',
    projectId: 'uberclone-4eb43',
    databaseURL: 'https://uberclone-4eb43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uberclone-4eb43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOsmv9vJ_8qK91fX7c6ml7MsTue_q-4FU',
    appId: '1:274499137654:ios:18cdc5aec2a6605bd82f57',
    messagingSenderId: '274499137654',
    projectId: 'uberclone-4eb43',
    databaseURL: 'https://uberclone-4eb43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uberclone-4eb43.firebasestorage.app',
    iosBundleId: 'com.example.taxiUserApp',
  );
}
